### PR TITLE
Add tickets menu item

### PR DESCRIPTION
**Pull request by adampiskorski**
New Ticket menu to contain "Ticket prices" and "Buy tickets" pages in order to make them easier to find (particularly when not at home page.) 
I believe that it's a better place than the About page and that it's among the most important menu items on a conference website and that the menu won't be too cluttered.

### CODE REVIEW

**Comment by hodgestar** [comment]
Willing to merge this, but betting there are going to be too many menus across the top now. :)

**Comment by hodgestar** [comment]
Also, someone will need to move the pages to the right menu in the admin interface after this is deployed.

**Comment by hodgestar** [comment]
Deployed and I've updated the menus via the admin interface.

**Comment by adampiskorski** [comment]
I'll ask others what they think about the number of menu items.
Thanks for moving the menu items, I was going to do it myself.

**Pull request merged**
